/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageProcessing;

/**
 *
 * @author Guilherme
 */
public class AboutShow extends javax.swing.JFrame {

    /**
     * Creates new form AboutShow
     */
    public AboutShow() {
        initComponents();
        this.setSize(700,500);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("CONTATOS:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 270, 610, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 70, 255));
        jLabel2.setText("Software THERMO FILM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 180, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Guilherme Machado, Mônica Voss, Juliano Smanioto Barin, Gilson Augusto Helfer, Adilson Ben da Costa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 50, 680, 40);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Programa de Pós-Graduação em Ciência e Tecnologia dos Alimentos");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 610, 40);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Programa de Pós-Graduação em Sistemas e Processos Industriais");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 170, 610, 40);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Programa de Pós-Graduação em Tecnologia Ambiental");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 200, 610, 40);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(70, 70, 255));
        jLabel7.setText("adilson@unisc.br");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 330, 440, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Universidade de Santa Cruz do Sul, 96815-900, Santa Cruz do Sul, Brasil");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 310, 490, 30);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(70, 70, 255));
        jLabel9.setText("Julino@ufsm.br");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 400, 440, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Universidade Federal de Santa Maria, 97105-900, Santa Maria, Brasil");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 380, 440, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
